/**
 * The curated core glossary — the "~130 core terms" ledger of the Interactive
 * Glossary brief. Hand-converted from the product owner's curated term sheet;
 * `def` and `example` are final copy (adapted from Wikipedia's Glossary of
 * contract bridge terms, CC BY-SA 4.0 — see Attribution.tsx) — don't rewrite
 * them casually. Each term is hand-mapped onto the brief's seven themes
 * (replacing the sheet's four categories); a term may carry several.
 *
 * `aliases` feed both search and the linkifier ("trump out" finds Drawing
 * trumps). `linkify: false` opts a term out of auto-linking in prose — used on
 * words so common in bid copy (bid, pass, game, trick…) that linking them
 * would turn every sentence into a link farm; they stay searchable and
 * openable. Tuning that flag is the intended noise dial for the linkifier.
 *
 * `related` slugs must resolve — web/src/glossary/glossary.test.ts enforces
 * that, along with slug uniqueness and theme coverage.
 */

export type GlossaryTheme = 'auction' | 'eval' | 'cardplay' | 'defense' | 'scoring' | 'conventions' | 'table';

/** Chip row order and labels, per the approved glossary design. */
export const THEMES: { id: GlossaryTheme; chip: string; name: string }[] = [
  { id: 'auction', chip: 'AUCTION', name: 'The Auction' },
  { id: 'eval', chip: 'EVAL', name: 'Hand Evaluation' },
  { id: 'cardplay', chip: 'CARD PLAY', name: 'Card Play' },
  { id: 'defense', chip: 'DEFENSE', name: 'Defense' },
  { id: 'scoring', chip: 'SCORING', name: 'Scoring & Duplicate' },
  { id: 'conventions', chip: 'CONVENTIONS', name: 'Conventions (SAYC)' },
  { id: 'table', chip: 'TABLE', name: 'Table & Roles' },
];

export const THEME_CHIP: Record<GlossaryTheme, string> = Object.fromEntries(
  THEMES.map((t) => [t.id, t.chip]),
) as Record<GlossaryTheme, string>;

export interface GlossaryTerm {
  /** kebab-case, unique — the /glossary/:slug deep-link id */
  slug: string;
  term: string;
  def: string;
  example?: string;
  themes: GlossaryTheme[];
  /** searchable synonyms; also matched by the linkifier */
  aliases?: string[];
  /** slugs of related core terms (rendered as chips on the entry sheet) */
  related?: string[];
  /** opt out of auto-linking in prose (still searchable/openable) */
  linkify?: false;
}

/** A–Z by term (digit-led terms first, under the '#' letter group). */
export const TERMS: GlossaryTerm[] = [
  {
    slug: '1nt-opening',
    term: '1NT opening',
    def: 'In SAYC, an opening bid showing a balanced hand with 15–17 HCP. The most descriptive single bid in the system.',
    example: 'With ♠KQ4 ♥AJ7 ♦KQ82 ♣J95, open 1NT.',
    themes: ['conventions', 'auction'],
    related: ['balanced-hand', 'stayman', 'jacoby-transfer'],
  },
  {
    slug: 'advancer',
    term: 'Advancer',
    def: 'The partner of the player who overcalled or doubled.',
    example: 'After (1♣) – 1♠ – (Pass), the next player to act for your side is the advancer.',
    themes: ['auction', 'table'],
    related: ['overcall', 'takeout-double'],
  },
  {
    slug: 'attitude-signal',
    term: 'Attitude signal',
    def: 'A signal telling partner whether you want the suit continued: standard is high = encourage, low = discourage.',
    example: 'Partner leads the ♥A; your ♥9 begs for more.',
    themes: ['defense'],
    aliases: ['attitude'],
    related: ['signal'],
  },
  {
    slug: 'auction',
    term: 'Auction',
    def: 'The first phase of every deal, where players take turns making calls to decide the final contract.',
    example: '1♥ – Pass – 2♥ – Pass… until three passes end it.',
    themes: ['auction'],
    aliases: ['bidding'],
    related: ['call', 'bid', 'contract'],
  },
  {
    slug: 'average',
    term: 'Average',
    def: 'Half the available matchpoints on a board — the 50% midpoint every result is measured against.',
    example: 'A dead-normal result lands near average.',
    themes: ['scoring'],
    related: ['percentage-score'],
    linkify: false,
  },
  {
    slug: 'balanced-hand',
    term: 'Balanced hand',
    def: 'A hand with no void, no singleton, and at most one doubleton (4–3–3–3, 4–4–3–2, or 5–3–3–2). The natural home of notrump bids.',
    example: '♠KQ4 ♥A73 ♦QJ82 ♣K95 is balanced.',
    themes: ['eval'],
    aliases: ['balanced'],
    related: ['notrump', 'shape'],
  },
  {
    slug: 'balancing',
    term: 'Balancing',
    def: 'Bidding in the passout seat to keep the auction alive when the opponents are about to buy it cheaply.',
    example: '(1♥) – P – (P) – 1♠ reopens.',
    themes: ['auction'],
    related: ['overcall', 'passed-out'],
  },
  {
    slug: 'bid',
    term: 'Bid',
    def: 'A call naming a level and a strain, offering to win that many tricks (plus the book of six) with that strain as trumps.',
    example: '2♠ offers to win 8 tricks with spades as trumps.',
    themes: ['auction'],
    related: ['level', 'strain', 'contract'],
    linkify: false,
  },
  {
    slug: 'bidding-system',
    term: 'Bidding system',
    def: 'A partnership’s complete set of agreements about what its calls mean.',
    example: 'SAYC, Acol, and 2/1 are systems.',
    themes: ['conventions'],
    related: ['sayc', 'convention'],
  },
  {
    slug: 'blackwood',
    term: 'Blackwood',
    def: 'A 4NT bid asking partner how many aces they hold, used to check that a slam isn’t missing two aces.',
    example: '4NT – 5♦ shows one ace.',
    themes: ['conventions'],
    related: ['slam', 'convention'],
  },
  {
    slug: 'blocked-suit',
    term: 'Blocked suit',
    def: 'A suit whose high cards in the short hand trap the lead there, so the long hand’s winners can’t be reached.',
    example: 'AK doubleton opposite QJxxx needs careful handling.',
    themes: ['cardplay'],
    aliases: ['blocked'],
    related: ['unblock', 'entry'],
  },
  {
    slug: 'board',
    term: 'Board',
    def: 'One deal as played and scored — in the app, one of the four identical deals every player in a tournament faces.',
    example: 'Board 3 of this week’s tournament.',
    themes: ['scoring'],
    related: ['deal', 'duplicate-bridge'],
    linkify: false,
  },
  {
    slug: 'book',
    term: 'Book',
    def: 'The first six tricks, always assumed and never counted in the bidding. A 1-level contract therefore promises seven tricks.',
    example: '1NT = 6 + 1 = 7 tricks.',
    themes: ['scoring', 'cardplay'],
    related: ['level', 'trick-points'],
  },
  {
    slug: 'bottom',
    term: 'Bottom',
    def: 'The worst result on a board — zero matchpoints. In matchpoints, minimizing bottoms matters as much as scoring tops.',
    example: '−1100 on a partscore deal is a likely bottom.',
    themes: ['scoring'],
    related: ['top', 'matchpoints'],
    linkify: false,
  },
  {
    slug: 'break',
    term: 'Break',
    def: 'How the opponents’ cards in a suit divide between their two hands.',
    example: 'Missing five cards, a 3–2 break is the friendly one.',
    themes: ['cardplay'],
    aliases: ['split'],
    related: ['shape'],
  },
  {
    slug: 'call',
    term: 'Call',
    def: 'Any action taken at your turn in the auction: a bid, pass, double, or redouble.',
    example: 'Pass is a call but not a bid.',
    themes: ['auction'],
    related: ['bid', 'pass', 'double'],
    linkify: false,
  },
  {
    slug: 'cash',
    term: 'Cash',
    def: 'To lead and win with a card that is currently top of its suit.',
    example: 'Cash the ♠AK before trying the finesse.',
    themes: ['cardplay'],
    related: ['winner'],
  },
  {
    slug: 'claim',
    term: 'Claim',
    def: 'Stating that the rest of the tricks are yours (or conceding some), ending the play early. Nickel Bridge auto-claims decided boards.',
    example: '‘Drawing trumps; the rest are mine.’',
    themes: ['cardplay'],
    related: ['winner', 'drawing-trumps'],
  },
  {
    slug: 'communication',
    term: 'Communication',
    def: 'The ability to move the lead between the two partnership hands at the right moments, managed through entries.',
    example: 'Cashing winners in the right order preserves communication.',
    themes: ['cardplay'],
    related: ['entry', 'unblock'],
  },
  {
    slug: 'competitive-auction',
    term: 'Competitive auction',
    def: 'An auction in which both partnerships bid.',
    example: '(1♦) – 1♠ – (2♦) – 2♠ …',
    themes: ['auction'],
    related: ['overcall', 'sacrifice'],
  },
  {
    slug: 'contract',
    term: 'Contract',
    def: 'The final bid of the auction: a promise by one side to win at least that many tricks in the named strain.',
    example: '4♥ commits declarer’s side to 10 tricks with hearts as trumps.',
    themes: ['auction'],
    related: ['level', 'strain', 'declarer'],
    linkify: false,
  },
  {
    slug: 'convention',
    term: 'Convention',
    def: 'An agreement giving a call an artificial, coded meaning unrelated to the suit named.',
    example: 'Stayman’s 2♣ says nothing about clubs.',
    themes: ['conventions'],
    related: ['stayman', 'blackwood', 'bidding-system'],
  },
  {
    slug: 'count-signal',
    term: 'Count signal',
    def: 'A signal showing an even or odd number of cards in the suit: standard is high-low = even.',
    example: 'Playing the 7 then the 2 shows an even count.',
    themes: ['defense'],
    related: ['signal'],
  },
  {
    slug: 'cover-an-honor',
    term: 'Cover an honor',
    def: 'Playing an honor on the opponents’ honor lead, aiming to promote lower cards for your side.',
    example: 'Dummy leads the queen; you cover with the king to promote partner’s 10.',
    themes: ['defense'],
    aliases: ['covering an honor'],
    related: ['honor', 'finesse'],
  },
  {
    slug: 'crossruff',
    term: 'Crossruff',
    def: 'Scoring trumps separately in both hands by ruffing different suits back and forth, instead of drawing trumps.',
    example: 'Ruff clubs in dummy, diamonds in hand, again and again.',
    themes: ['cardplay'],
    aliases: ['cross-ruff'],
    related: ['ruff', 'drawing-trumps'],
  },
  {
    slug: 'cue-bid',
    term: 'Cue bid',
    def: 'A bid of the opponents’ suit (showing strength or a raise) or, in slam auctions, a bid showing a control in that suit.',
    example: '(1♥) – Dbl – (P) – 2♥ shows a strong advance.',
    themes: ['auction', 'conventions'],
    aliases: ['cuebid', 'cue-bid'],
    related: ['convention', 'slam'],
  },
  {
    slug: 'danger-hand',
    term: 'Danger hand',
    def: 'The opponent you cannot afford to see on lead, because their return would hurt you.',
    example: 'Keep East off lead so no heart comes through your king.',
    themes: ['cardplay'],
    related: ['holdup', 'finesse'],
  },
  {
    slug: 'deal',
    term: 'Deal',
    def: 'One specific arrangement of the 52 cards into four hands.',
    example: 'Everyone in a Nickel Bridge tournament plays the same four deals.',
    themes: ['scoring', 'table'],
    related: ['board', 'dealer'],
    linkify: false,
  },
  {
    slug: 'dealer',
    term: 'Dealer',
    def: 'The player designated to make the first call on a board. It rotates from board to board.',
    example: 'On Board 2, East is dealer and calls first.',
    themes: ['table'],
    related: ['deal', 'auction'],
  },
  {
    slug: 'declarer',
    term: 'Declarer',
    def: 'The player who first named the strain of the final contract. Declarer plays both their own hand and dummy’s.',
    example: 'In Nickel Bridge you’re South, and often declarer.',
    themes: ['table'],
    related: ['dummy', 'contract'],
  },
  {
    slug: 'defender',
    term: 'Defender',
    def: 'Either member of the pair that did not win the auction; their goal is to defeat the contract.',
    example: 'Defenders win by taking enough tricks to set declarer.',
    themes: ['table', 'defense'],
    related: ['declarer', 'down'],
  },
  {
    slug: 'discard',
    term: 'Discard',
    def: 'Playing a card of a different, non-trump suit when you can’t follow suit. It can never win the trick.',
    example: 'Out of hearts, you throw the ♣2.',
    themes: ['cardplay', 'defense'],
    related: ['follow-suit', 'ruff', 'signal'],
  },
  {
    slug: 'distribution-points',
    term: 'Distribution points',
    def: 'Extra points added for shape — typically for short suits once a trump fit is found (void 3, singleton 2, doubleton 1).',
    example: 'A singleton club adds 2 points in a spade fit.',
    themes: ['eval'],
    related: ['hcp', 'shape'],
  },
  {
    slug: 'double',
    term: 'Double',
    def: 'A call that raises the stakes on the opponents’ contract — bigger penalties if it fails, bigger rewards if it makes. Many doubles carry a conventional meaning instead.',
    example: '(4♠) – Double, expecting to beat it.',
    themes: ['auction'],
    related: ['penalty-double', 'takeout-double', 'redouble'],
    linkify: false,
  },
  {
    slug: 'doubled-contract',
    term: 'Doubled contract',
    def: 'A contract played after a double: trick points and penalties are multiplied, and making it earns an extra 50 (‘for the insult’).',
    example: '2♠ doubled and made = game score.',
    themes: ['scoring'],
    aliases: ['doubled'],
    related: ['double', 'penalty-points'],
  },
  {
    slug: 'doubleton',
    term: 'Doubleton',
    def: 'Exactly two cards in a suit.',
    example: '♥95 is a doubleton.',
    themes: ['eval'],
    related: ['singleton', 'balanced-hand'],
  },
  {
    slug: 'down',
    term: 'Down',
    def: 'Failing to make the contract, described by the number of missing tricks.',
    example: '‘Down one’ — declarer was one trick short.',
    themes: ['scoring'],
    related: ['undertrick', 'defender'],
    linkify: false,
  },
  {
    slug: 'drawing-trumps',
    term: 'Drawing trumps',
    def: 'Leading trumps until the opponents have none left, so your winners can’t be ruffed.',
    example: 'With 9 trumps between the hands, usually two or three rounds does it.',
    themes: ['cardplay'],
    aliases: ['draw trumps', 'pulling trumps', 'trump out'],
    related: ['trump', 'ruff'],
  },
  {
    slug: 'duck',
    term: 'Duck',
    def: 'Deliberately not winning a trick you could win, keeping a high card back for a better moment.',
    example: 'Holding ♥A against 3NT, you let their king win the first heart.',
    themes: ['cardplay'],
    aliases: ['ducking'],
    related: ['holdup'],
  },
  {
    slug: 'dummy',
    term: 'Dummy',
    def: 'Declarer’s partner. After the opening lead, dummy’s cards go face up and declarer chooses every card played from them.',
    example: 'North’s hand hits the table; South runs the show.',
    themes: ['table'],
    related: ['declarer'],
  },
  {
    slug: 'duplicate-bridge',
    term: 'Duplicate bridge',
    def: 'The form of bridge where every player plays the identical deals and results are compared — removing card luck so only judgment is measured. It’s what Nickel Bridge is.',
    example: 'Your 4♠ is compared with everyone else’s result on the same board.',
    themes: ['scoring'],
    aliases: ['duplicate'],
    related: ['board', 'matchpoints'],
  },
  {
    slug: 'eight-ever-nine-never',
    term: 'Eight ever, nine never',
    def: 'The classic memory aid for a missing queen: finesse with eight cards in the suit, play for the drop with nine.',
    example: 'Like all maxims, it bends to what the auction told you.',
    themes: ['cardplay'],
    related: ['finesse'],
  },
  {
    slug: 'elo-rating',
    term: 'Elo rating',
    def: 'Nickel Bridge’s long-term skill rating, recomputed from the full history of head-to-head board results every time new results arrive.',
    example: 'Beating higher-rated friends on a board moves you up more.',
    themes: ['scoring'],
    aliases: ['Elo', 'nickel rating'],
    related: ['percentage-score', 'field'],
  },
  {
    slug: 'entry',
    term: 'Entry',
    def: 'A card that lets a particular hand win a trick, so play can continue from that hand.',
    example: 'Dummy’s ♣A is the only way to reach dummy’s established diamonds.',
    themes: ['cardplay'],
    related: ['communication', 'blocked-suit'],
  },
  {
    slug: 'establish',
    term: 'Establish',
    def: 'Turning small cards into winners by forcing out all higher cards in the suit.',
    example: 'Knock out the ♦A twice and your remaining diamonds are good.',
    themes: ['cardplay'],
    aliases: ['established', 'establishing'],
    related: ['winner', 'long-suit', 'stopper'],
  },
  {
    slug: 'field',
    term: 'Field',
    def: 'Everyone playing the same boards — the group your result is compared against. In the app, the tournament (or, with Clubs, your club).',
    example: 'Bidding a thin game ‘against the field’ is a matchpoint gamble.',
    themes: ['scoring'],
    related: ['matchpoints', 'duplicate-bridge'],
  },
  {
    slug: 'finesse',
    term: 'Finesse',
    def: 'Trying to win a trick with a lower honor by leading toward it, hoping the missing higher card sits in front of it — a 50% play made free.',
    example: 'Lead low toward AQ, playing the Q if LHO plays low.',
    themes: ['cardplay'],
    aliases: ['hook', 'finessing'],
    related: ['tenace', 'eight-ever-nine-never'],
  },
  {
    slug: 'fit',
    term: 'Fit',
    def: 'Eight or more cards in one suit between the two partnership hands — the threshold for a comfortable trump suit.',
    example: '5 hearts opposite 3 hearts is an 8-card fit.',
    themes: ['auction', 'eval'],
    aliases: ['golden fit', 'trump fit'],
    related: ['raise'],
  },
  {
    slug: 'five-card-majors',
    term: 'Five-card majors',
    def: 'The SAYC agreement that opening 1♥ or 1♠ promises at least five cards in the suit.',
    example: 'With 4 spades and 4 diamonds, open 1♦, not 1♠.',
    themes: ['conventions'],
    related: ['sayc', 'major-suit'],
  },
  {
    slug: 'follow-suit',
    term: 'Follow suit',
    def: 'The obligation to play a card of the suit led if you have one. Only when you’re out may you play another suit.',
    example: 'A heart is led; holding a heart, you must play it.',
    themes: ['cardplay'],
    aliases: ['following suit'],
    related: ['revoke', 'discard'],
  },
  {
    slug: 'forcing-bid',
    term: 'Forcing bid',
    def: 'A bid that, by agreement, partner must not pass. New suits by responder are forcing in SAYC.',
    example: '1♣ – 1♠ cannot be passed.',
    themes: ['auction'],
    aliases: ['forcing'],
    related: ['sign-off', 'response'],
  },
  {
    slug: 'game',
    term: 'Game',
    def: 'A contract worth 100+ trick points: 3NT, 4♥/4♠, or 5♣/5♦. Bidding and making it earns a large bonus.',
    example: 'With 25+ combined points, bid game.',
    themes: ['auction', 'scoring'],
    related: ['game-bonus', 'part-score'],
    linkify: false,
  },
  {
    slug: 'game-bonus',
    term: 'Game bonus',
    def: 'The reward for bidding and making game: 300 not vulnerable, 500 vulnerable. The engine that drives all bidding decisions.',
    example: 'It’s why 4♠ scores 420 and 2♠+2 only 170.',
    themes: ['scoring'],
    related: ['game', 'vulnerability'],
  },
  {
    slug: 'game-try',
    term: 'Game try',
    def: 'After a single raise, a new-suit bid asking partner to evaluate for game — often showing where help is needed.',
    example: '1♠ – 2♠; 3♣ asks about club help.',
    themes: ['auction'],
    related: ['invitational-bid', 'raise'],
  },
  {
    slug: 'grand-slam',
    term: 'Grand slam',
    def: 'A 7-level contract: your side must win every trick.',
    example: '7NT is the highest possible contract.',
    themes: ['auction', 'scoring'],
    related: ['slam', 'blackwood'],
  },
  {
    slug: 'hand-evaluation',
    term: 'Hand evaluation',
    def: 'Judging what a hand is worth by combining HCP, shape, and how the hands fit together.',
    example: '12 HCP with a 6-card suit is worth more than a flat 12.',
    themes: ['eval'],
    related: ['hcp', 'distribution-points'],
  },
  {
    slug: 'hcp',
    term: 'High card points',
    def: 'The standard measure of hand strength: Ace = 4, King = 3, Queen = 2, Jack = 1. A full deck holds 40.',
    example: '♠AK is 7 HCP.',
    themes: ['eval'],
    aliases: ['HCP', 'high-card points'],
    related: ['hand-evaluation', 'distribution-points'],
  },
  {
    slug: 'holdup',
    term: 'Holdup',
    def: 'Declarer’s duck — refusing to take a winner early to cut the defenders’ link in their long suit.',
    example: 'Take the ♠A on the third round, exhausting East’s spades.',
    themes: ['cardplay'],
    aliases: ['hold-up'],
    related: ['duck', 'danger-hand'],
  },
  {
    slug: 'honor',
    term: 'Honor',
    def: 'An ace, king, queen, jack, or ten.',
    example: 'AKQJ10 are the honors in each suit.',
    themes: ['cardplay', 'eval'],
    aliases: ['honour'],
    related: ['hcp', 'spot-card'],
  },
  {
    slug: 'imp',
    term: 'IMP',
    def: 'International Match Points — the team-scoring scale that converts score differences into a compressed 0–24 range. Not used in Nickel Bridge (we matchpoint), but you’ll meet it elsewhere.',
    example: 'A 500-point swing ≈ 11 IMPs.',
    themes: ['scoring'],
    aliases: ['international match points'],
    related: ['matchpoints'],
  },
  {
    slug: 'invitational-bid',
    term: 'Invitational bid',
    def: 'A bid asking partner to carry on to game with a maximum and stop with a minimum.',
    example: '1NT – 2NT invites 3NT.',
    themes: ['auction'],
    aliases: ['invitational', 'invitation', 'invite'],
    related: ['limit-raise', 'game-try'],
  },
  {
    slug: 'jacoby-transfer',
    term: 'Jacoby transfer',
    def: 'Over 1NT, a bid of 2♦ or 2♥ asking opener to bid the next suit up, so the strong hand declares responder’s major.',
    example: '1NT – 2♥ (transfer); 2♠.',
    themes: ['conventions'],
    aliases: ['transfer'],
    related: ['1nt-opening', 'stayman', 'convention'],
  },
  {
    slug: 'jump-bid',
    term: 'Jump bid',
    def: 'A bid one or more levels higher than necessary, used to show extra strength or (in some auctions) to preempt.',
    example: '1♣ – 2♠ skips 1♠, so it is a jump.',
    themes: ['auction'],
    related: ['preempt', 'limit-raise'],
  },
  {
    slug: 'lead',
    term: 'Lead',
    def: 'The first card played to a trick. Winning a trick earns the right to lead to the next one.',
    example: 'Whoever wins trick 3 leads to trick 4.',
    themes: ['cardplay'],
    related: ['opening-lead'],
    linkify: false,
  },
  {
    slug: 'level',
    term: 'Level',
    def: 'The number part of a bid, from 1 to 7. Add six (the book) to get the tricks promised.',
    example: 'The 3 in 3NT means nine tricks.',
    themes: ['auction'],
    related: ['book', 'contract'],
    linkify: false,
  },
  {
    slug: 'lho-rho',
    term: 'LHO / RHO',
    def: 'Left-hand opponent and right-hand opponent — the players sitting to your left and right.',
    example: 'Your RHO plays just before you on each trick.',
    themes: ['table'],
    aliases: ['LHO', 'RHO', 'left-hand opponent', 'right-hand opponent'],
    related: ['defender'],
  },
  {
    slug: 'limit-raise',
    term: 'Limit raise',
    def: 'A double raise of partner’s suit showing invitational strength (about 10–12 points) and support.',
    example: '1♠ – 3♠ invites opener to bid game with extras.',
    themes: ['auction'],
    related: ['raise', 'invitational-bid'],
  },
  {
    slug: 'long-suit',
    term: 'Long suit',
    def: 'A suit of five or more cards — the raw material for extra tricks, since its small cards win once everyone else runs out.',
    example: 'The 13th card of a suit always wins.',
    themes: ['eval', 'cardplay'],
    related: ['establish'],
  },
  {
    slug: 'loser',
    term: 'Loser',
    def: 'A card in declarer’s plan that figures to lose a trick unless something is done about it.',
    example: 'Counting losers is step one of every trump-contract plan.',
    themes: ['cardplay'],
    related: ['winner', 'ruff'],
  },
  {
    slug: 'major-suit',
    term: 'Major suit',
    def: 'Hearts and spades. They score 30 points per trick, so game needs only the 4 level.',
    example: '4♠ = game; 10 tricks.',
    themes: ['auction'],
    aliases: ['major'],
    related: ['minor-suit', 'game'],
  },
  {
    slug: 'making',
    term: 'Making',
    def: 'Taking at least as many tricks as the contract promised.',
    example: '3NT making four = contract plus one overtrick.',
    themes: ['scoring'],
    related: ['overtrick', 'score'],
    linkify: false,
  },
  {
    slug: 'matchpoints',
    term: 'Matchpoints',
    def: 'The pairs scoring method: on each board you earn one matchpoint per pair you beat and half per pair you tie — then it’s shown as a percentage.',
    example: 'Beating 6 of 8 comparable scores ≈ 75% on the board.',
    themes: ['scoring'],
    aliases: ['matchpoint', 'matchpointing'],
    related: ['top', 'percentage-score'],
  },
  {
    slug: 'minor-suit',
    term: 'Minor suit',
    def: 'Clubs and diamonds. They score 20 per trick, so game needs the 5 level — which is why pairs prefer major or NT games.',
    example: '5♦ = game; 11 tricks.',
    themes: ['auction'],
    aliases: ['minor'],
    related: ['major-suit', 'game'],
  },
  {
    slug: 'notrump',
    term: 'Notrump',
    def: 'A strain with no trump suit at all: the highest card of the suit led always wins the trick.',
    example: '3NT is the most common game contract.',
    themes: ['auction'],
    aliases: ['NT', 'no trump', 'no-trump'],
    related: ['strain', 'balanced-hand'],
  },
  {
    slug: 'opener',
    term: 'Opener',
    def: 'The player who makes the opening bid.',
    example: 'After 1♠, that player is the opener for the rest of the auction.',
    themes: ['auction', 'table'],
    related: ['opening-bid', 'responder'],
  },
  {
    slug: 'opening-bid',
    term: 'Opening bid',
    def: 'The first bid of the auction. Making it usually promises about 12+ points.',
    example: '1♣ as the first bid of the deal is an opening bid.',
    themes: ['auction'],
    aliases: ['open', 'opening'],
    related: ['opener', 'hcp'],
  },
  {
    slug: 'opening-lead',
    term: 'Opening lead',
    def: 'The very first card of the play, made by the player to declarer’s left before dummy appears.',
    example: 'Against 3NT, West leads the ♥4 — fourth from their longest suit.',
    themes: ['defense', 'cardplay'],
    related: ['lead', 'defender'],
  },
  {
    slug: 'overcall',
    term: 'Overcall',
    def: 'A bid made after an opponent has opened, showing a decent suit and competing for the contract.',
    example: '(1♣) – 1♠ is a spade overcall.',
    themes: ['auction'],
    related: ['advancer', 'competitive-auction'],
  },
  {
    slug: 'overruff',
    term: 'Overruff',
    def: 'Ruffing with a higher trump after an opponent has already ruffed the trick.',
    example: 'They ruff with the ♠5; you overruff with the ♠9.',
    themes: ['cardplay'],
    related: ['ruff'],
  },
  {
    slug: 'overtrick',
    term: 'Overtrick',
    def: 'A trick taken beyond the contract. Nice, but worth far less than tricks bid.',
    example: '4♠ with 11 tricks = one overtrick.',
    themes: ['scoring'],
    related: ['undertrick', 'matchpoints'],
  },
  {
    slug: 'part-score',
    term: 'Part score',
    def: 'A contract below game, worth its trick points plus a modest 50-point bonus.',
    example: '2♠ making = 110.',
    themes: ['scoring'],
    aliases: ['part-score', 'partscore', 'partial'],
    related: ['game', 'score'],
  },
  {
    slug: 'pass',
    term: 'Pass',
    def: 'A call that makes no bid. Three passes in a row after any bid end the auction.',
    example: 'With 4 HCP you usually pass.',
    themes: ['auction'],
    related: ['call', 'passed-out'],
    linkify: false,
  },
  {
    slug: 'passed-out',
    term: 'Passed out',
    def: 'A deal on which all four players pass with no bid made; it is scored as zero for both sides.',
    example: 'Pass – Pass – Pass – Pass.',
    themes: ['auction'],
    aliases: ['pass out', 'passout'],
    related: ['pass'],
  },
  {
    slug: 'penalty-double',
    term: 'Penalty double',
    def: 'A double intended literally: you believe the opponents cannot make their contract.',
    example: 'Doubling a 5♣ sacrifice for penalties.',
    themes: ['auction'],
    related: ['double', 'sacrifice'],
  },
  {
    slug: 'penalty-points',
    term: 'Penalty points',
    def: 'What a failed contract pays the defenders — 50 or 100 per undertrick, climbing steeply when doubled.',
    example: 'Down 3 doubled vulnerable = −800.',
    themes: ['scoring'],
    related: ['undertrick', 'double'],
  },
  {
    slug: 'percentage-score',
    term: 'Percentage score',
    def: 'Your matchpoints as a share of the maximum available; 50% is exactly average.',
    example: '55%+ over a session is a good game.',
    themes: ['scoring'],
    related: ['matchpoints', 'average'],
  },
  {
    slug: 'preempt',
    term: 'Preempt',
    def: 'A high-level opening or jump with a long suit and a weak hand, made to steal bidding space from the opponents.',
    example: '3♣ over nothing, with 7 clubs and 6 HCP.',
    themes: ['auction'],
    aliases: ['pre-empt', 'preemptive bid'],
    related: ['weak-two-bid', 'sacrifice'],
  },
  {
    slug: 'raise',
    term: 'Raise',
    def: 'Supporting partner’s suit by bidding it at a higher level, promising a fit.',
    example: '1♥ – 2♥ shows heart support and 6–9 points.',
    themes: ['auction'],
    related: ['fit', 'limit-raise'],
  },
  {
    slug: 'rebid',
    term: 'Rebid',
    def: 'A player’s second (or later) bid, refining the picture their first bid painted.',
    example: '1♣ then 1NT next turn shows a balanced minimum.',
    themes: ['auction'],
    related: ['opener', 'response'],
  },
  {
    slug: 'redouble',
    term: 'Redouble',
    def: 'A call available after the opponents double, doubling the stakes again — or, conventionally, showing strength.',
    example: '1♠ – (Dbl) – Redouble shows 10+ points.',
    themes: ['auction'],
    related: ['double'],
  },
  {
    slug: 'responder',
    term: 'Responder',
    def: 'The partner of the player who opened the bidding.',
    example: 'Opener shows their hand first; responder steers the pair toward the right contract.',
    themes: ['auction', 'table'],
    related: ['response', 'opener'],
  },
  {
    slug: 'response',
    term: 'Response',
    def: 'The first call made by the opener’s partner, describing their strength and shape.',
    example: '1♠ – Pass – 2♠ is a response.',
    themes: ['auction'],
    related: ['responder', 'raise'],
  },
  {
    slug: 'revoke',
    term: 'Revoke',
    def: 'Failing to follow suit while able to — an illegal play that carries penalties in live bridge. The app simply won’t let you.',
    example: 'Playing a club while holding a heart when hearts were led.',
    themes: ['cardplay'],
    aliases: ['renege'],
    related: ['follow-suit'],
  },
  {
    slug: 'robot-partner',
    term: 'Robot partner',
    def: 'The app’s deterministic AI partner and opponents: they bid and play identically for every player on the same deal, which is what makes score comparison fair.',
    example: 'Your North always makes the same call in the same auction.',
    themes: ['table'],
    aliases: ['robot'],
    related: ['duplicate-bridge'],
  },
  {
    slug: 'ruff',
    term: 'Ruff',
    def: 'Playing a trump when you cannot follow suit, usually winning the trick.',
    example: 'Void in clubs, you ruff with the ♠5.',
    themes: ['cardplay'],
    aliases: ['ruffing', 'trumping'],
    related: ['trump', 'void', 'overruff'],
  },
  {
    slug: 'sacrifice',
    term: 'Sacrifice',
    def: 'Deliberately bidding a contract you expect to fail because going down will cost less than the opponents’ making game or slam.',
    example: '5♣ over their 4♠, down 2 for −300 vs their −620.',
    themes: ['auction', 'scoring'],
    related: ['penalty-double', 'vulnerability'],
  },
  {
    slug: 'sayc',
    term: 'SAYC',
    def: 'Standard American Yellow Card — the widely-played system Nickel Bridge teaches: five-card majors, 15–17 1NT, weak twos.',
    example: 'Every bid explanation in the app assumes SAYC.',
    themes: ['conventions'],
    aliases: ['Standard American', 'Standard American Yellow Card'],
    related: ['bidding-system', 'five-card-majors'],
  },
  {
    slug: 'score',
    term: 'Score',
    def: 'The points awarded after each board, based on the contract, tricks taken, doubling, and vulnerability.',
    example: '4♠ making exactly, not vulnerable: +420.',
    themes: ['scoring'],
    related: ['trick-points', 'game-bonus'],
    linkify: false,
  },
  {
    slug: 'second-hand-low',
    term: 'Second hand low',
    def: 'The rule of thumb that the second player to a trick usually plays low, saving honors to capture honors.',
    example: 'Declarer leads low; don’t fly with your king for no reason.',
    themes: ['defense'],
    related: ['third-hand-high'],
  },
  {
    slug: 'sequence',
    term: 'Sequence',
    def: 'Two or more touching honors, like KQJ. Leading the top of a sequence is a safe, standard opening lead.',
    example: 'From KQJ4, lead the king.',
    themes: ['cardplay', 'defense'],
    related: ['opening-lead', 'honor'],
  },
  {
    slug: 'shape',
    term: 'Shape',
    def: 'How a hand’s 13 cards are split across the four suits, e.g. 5–4–3–1. Also called distribution or pattern.',
    example: 'A 7–4–1–1 hand is wildly shapely.',
    themes: ['eval'],
    aliases: ['distribution'],
    related: ['balanced-hand', 'singleton', 'void'],
  },
  {
    slug: 'sign-off',
    term: 'Sign-off',
    def: 'A bid intended to end the auction; partner is expected to pass.',
    example: '1NT – 2♥ – 2♠ – Pass: the transfer completion was passed.',
    themes: ['auction'],
    aliases: ['signoff', 'sign off'],
    related: ['forcing-bid'],
  },
  {
    slug: 'signal',
    term: 'Signal',
    def: 'A defender’s choice of card used as a legal message to partner — encouraging, discouraging, or showing count.',
    example: 'A high spot says ‘I like this suit.’',
    themes: ['defense'],
    aliases: ['carding'],
    related: ['attitude-signal', 'count-signal'],
  },
  {
    slug: 'singleton',
    term: 'Singleton',
    def: 'Exactly one card in a suit.',
    example: 'A singleton king is a nervous holding.',
    themes: ['eval'],
    related: ['void', 'doubleton'],
  },
  {
    slug: 'slam',
    term: 'Slam',
    def: 'A 6-level contract (small slam, 12 tricks) or 7-level contract (grand slam, all 13). Both pay big bonuses.',
    example: '6NT making earns the small-slam bonus.',
    themes: ['auction', 'scoring'],
    aliases: ['small slam'],
    related: ['grand-slam', 'blackwood', 'slam-bonus'],
  },
  {
    slug: 'slam-bonus',
    term: 'Slam bonus',
    def: 'The extra bonus for a made slam: 500/750 for small slams, 1000/1500 for grands (non-vul/vul).',
    example: '6♥ vulnerable making: +1430.',
    themes: ['scoring'],
    related: ['slam', 'vulnerability'],
  },
  {
    slug: 'spot-card',
    term: 'Spot card',
    def: 'Any card from the 9 down to the 2.',
    example: 'Good spots like the 9 and 8 quietly win tricks.',
    themes: ['cardplay'],
    aliases: ['spot'],
    related: ['honor'],
  },
  {
    slug: 'stayman',
    term: 'Stayman',
    def: 'A 2♣ response to 1NT asking opener to show a 4-card major. It says nothing about clubs.',
    example: '1NT – 2♣; 2♥ shows four hearts.',
    themes: ['conventions'],
    related: ['1nt-opening', 'jacoby-transfer', 'convention'],
  },
  {
    slug: 'stopper',
    term: 'Stopper',
    def: 'A holding that prevents the opponents from immediately running a suit against notrump — an ace, or a guarded lower honor.',
    example: '♥Kx is a likely heart stopper.',
    themes: ['auction', 'cardplay'],
    related: ['notrump', 'establish'],
  },
  {
    slug: 'strain',
    term: 'Strain',
    def: 'The suit part of a bid — clubs, diamonds, hearts, spades, or notrump. Also called the denomination.',
    example: 'In 4♥, hearts is the strain.',
    themes: ['auction'],
    aliases: ['denomination'],
    related: ['level', 'notrump'],
  },
  {
    slug: 'takeout-double',
    term: 'Takeout double',
    def: 'A double of an opponent’s low-level bid asking partner to bid their best suit, showing support for the unbid suits.',
    example: '(1♥) – Double with 4 spades and both minors.',
    themes: ['conventions', 'auction'],
    related: ['double', 'advancer'],
  },
  {
    slug: 'tenace',
    term: 'Tenace',
    def: 'Two honors with a gap, like AQ — worth extra when the missing card sits in front of it.',
    example: 'AQ over the king takes two tricks via the finesse.',
    themes: ['cardplay'],
    related: ['finesse'],
  },
  {
    slug: 'third-hand-high',
    term: 'Third hand high',
    def: 'The rule of thumb that the third player to a trick plays their highest card to fight for it for partner’s side.',
    example: 'Partner leads the ♥4; dummy plays low; you play your king.',
    themes: ['defense'],
    related: ['second-hand-low'],
  },
  {
    slug: 'toll-ticket',
    term: 'Toll ticket',
    def: 'The app’s results card for a board or session: contract, tricks, score, matchpoints, and rating change — stamped like a bridge toll receipt.',
    example: 'Every crossing ends with one — learn to read each line of it.',
    themes: ['scoring'],
    aliases: ['toll receipt'],
    related: ['elo-rating', 'matchpoints'],
  },
  {
    slug: 'top',
    term: 'Top',
    def: 'The best result on a board among all who played it — full matchpoints.',
    example: 'Your +650 beat every other table: a cold top.',
    themes: ['scoring'],
    related: ['bottom', 'matchpoints'],
    linkify: false,
  },
  {
    slug: 'trick',
    term: 'Trick',
    def: 'Four cards, one from each player in clockwise turn. The highest card of the suit led wins it — unless a trump appears.',
    example: '13 tricks are played on every deal.',
    themes: ['cardplay'],
    related: ['follow-suit', 'trump'],
    linkify: false,
  },
  {
    slug: 'trick-points',
    term: 'Trick points',
    def: 'Points for tricks bid and made: 20 each for minors, 30 each for majors, and 40-then-30 for notrump.',
    example: '3NT = 40 + 30 + 30 = 100.',
    themes: ['scoring'],
    related: ['game', 'score'],
  },
  {
    slug: 'trump',
    term: 'Trump',
    def: 'The boss suit named by the contract. Any trump beats any card of another suit.',
    example: 'With spades trump, the ♠2 beats the ♥A.',
    themes: ['cardplay'],
    related: ['ruff', 'strain'],
    linkify: false,
  },
  {
    slug: 'unblock',
    term: 'Unblock',
    def: 'Playing away a high card that would otherwise strand the lead in the wrong hand.',
    example: 'Drop your ♦K under the ace so partner’s long diamonds can run.',
    themes: ['cardplay'],
    aliases: ['unblocking'],
    related: ['blocked-suit', 'entry'],
  },
  {
    slug: 'undertrick',
    term: 'Undertrick',
    def: 'Each trick by which a failing contract falls short; each costs penalty points to the declaring side.',
    example: '4♠ with 8 tricks = down 2.',
    themes: ['scoring'],
    related: ['down', 'penalty-points'],
  },
  {
    slug: 'void',
    term: 'Void',
    def: 'Zero cards in a suit. In a trump contract, a void lets you ruff that suit immediately.',
    example: '♠AKQ52 ♥QJ973 ♦K84 ♣— has a club void.',
    themes: ['eval', 'cardplay'],
    related: ['singleton', 'ruff'],
  },
  {
    slug: 'vulnerability',
    term: 'Vulnerability',
    def: 'A per-board condition (marked red in the app) that raises both bonuses and penalties. It rotates through the boards automatically.',
    example: 'Vulnerable game bonus 500; vulnerable doubled undertricks sting.',
    themes: ['scoring'],
    aliases: ['vulnerable', 'vul'],
    related: ['game-bonus', 'sacrifice'],
  },
  {
    slug: 'weak-two-bid',
    term: 'Weak two bid',
    def: 'An opening of 2♦, 2♥, or 2♠ showing a good 6-card suit and 5–10 HCP — the mildest preempt.',
    example: '2♠ with ♠KQJ973 and little else.',
    themes: ['auction', 'conventions'],
    aliases: ['weak two'],
    related: ['preempt'],
  },
  {
    slug: 'winner',
    term: 'Winner',
    def: 'A card that will take a trick when led — the highest still out in its suit.',
    example: 'After the ace and king are gone, your queen is a winner.',
    themes: ['cardplay'],
    related: ['loser', 'cash'],
  },
];

export const TERM_BY_SLUG: ReadonlyMap<string, GlossaryTerm> = new Map(TERMS.map((t) => [t.slug, t]));
