/**
 * IndexNow submission — push the glossary URLs at the search engines that
 * accept being told.
 *
 * WHY THIS EXISTS. Google and Bing both retired their anonymous
 * `ping?sitemap=` endpoints (2023–24), so there is no longer any unauthenticated
 * way to say "this changed, come look." IndexNow is the replacement, and the
 * only push-based submission a machine can still perform: one POST to
 * api.indexnow.org fans out to every participant — Bing, Yandex, Seznam,
 * Naver. **Google does not participate**, so this complements Search Console
 * rather than replacing it; Google still discovers the sitemap via robots.txt.
 *
 * The protocol authenticates by fetching a key file from the host you're
 * submitting for, which `server/src/app.ts` serves when INDEXNOW_KEY is set
 * (never on a DEMO/DEV_AUTH origin — a preview must not claim a key).
 *
 *   INDEXNOW_KEY=<key> node scripts/indexnow.mjs                     # production
 *   INDEXNOW_KEY=<key> node scripts/indexnow.mjs --dry-run           # show, don't send
 *   INDEXNOW_KEY=<key> node scripts/indexnow.mjs http://localhost:3000 --dry-run
 *
 * Generate a key once (any 8–128 chars of [a-zA-Z0-9-]) and set it as a Fly
 * secret on the production app so the server serves the matching key file:
 *
 *   node -e "console.log(crypto.randomUUID().replaceAll('-',''))"
 *   fly secrets set INDEXNOW_KEY=<key> --app nickel-bridge
 *
 * DELIBERATELY MANUAL. IndexNow asks you to submit URLs that actually changed;
 * re-submitting 127 unchanged pages on every deploy is exactly what its docs
 * tell you not to do. The glossary changes when someone edits terms.ts, which
 * is rare and deliberate — so this runs when that happens, not from CI.
 */
const ENDPOINT = 'https://api.indexnow.org/indexnow';

const args = process.argv.slice(2);
const dryRun = args.includes('--dry-run');
const base = (args.find((a) => !a.startsWith('--')) ?? 'https://bridge.brannon.online').replace(/\/+$/, '');

const key = process.env.INDEXNOW_KEY;
if (!key) {
  console.error('INDEXNOW_KEY is not set. See this file’s header for how to generate one.');
  process.exit(1);
}
if (!/^[a-zA-Z0-9-]{8,128}$/.test(key)) {
  console.error('INDEXNOW_KEY must be 8–128 characters of [a-zA-Z0-9-] — the protocol rejects anything else.');
  process.exit(1);
}

const { host } = new URL(base);
const keyLocation = `${base}/${key}.txt`;

/**
 * fetch with a deadline. Node's fetch has none by default, so an unreachable
 * or hung host would leave this waiting forever — the one failure mode that
 * wouldn't produce the actionable message every other path here gives.
 */
async function fetchOrExit(url, init = {}, ms = 15_000) {
  try {
    return await fetch(url, { ...init, signal: AbortSignal.timeout(ms) });
  } catch (err) {
    const name = err?.name;
    console.error(
      name === 'TimeoutError' || name === 'AbortError'
        ? `Timed out after ${ms / 1000}s fetching ${url}`
        : `Could not reach ${url} — ${err?.message ?? err}`,
    );
    process.exit(1);
  }
}

/** Verify the host actually serves the key before submitting, so a
 *  misconfigured deployment fails here with a clear message rather than as an
 *  opaque 403 from the API. */
const keyRes = await fetchOrExit(keyLocation);
const keyBody = keyRes.ok ? (await keyRes.text()).trim() : '';
if (!keyRes.ok || keyBody !== key) {
  console.error(`Key file check failed at ${keyLocation}`);
  console.error(
    keyRes.ok
      ? `  served ${JSON.stringify(keyBody.slice(0, 40))}, expected the key itself`
      : `  HTTP ${keyRes.status} — is INDEXNOW_KEY set on that deployment, and is it not a DEMO/DEV_AUTH origin?`,
  );
  process.exit(1);
}
console.log(`key file OK at ${keyLocation}`);

// The sitemap is ours and generated by web/scripts/prerender-glossary.mjs, so a
// <loc> scan is enough — no XML dependency for a file whose exact shape we emit.
const sitemapUrl = `${base}/sitemap.xml`;
const sitemapRes = await fetchOrExit(sitemapUrl);
if (!sitemapRes.ok) {
  console.error(`Could not fetch ${sitemapUrl} — HTTP ${sitemapRes.status}`);
  process.exit(1);
}
const urlList = [...(await sitemapRes.text()).matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1].trim());

const foreign = urlList.filter((u) => new URL(u).host !== host);
if (!urlList.length || foreign.length) {
  console.error(
    !urlList.length ? `No <loc> entries in ${sitemapUrl}` : `Sitemap contains URLs off ${host}: ${foreign[0]} …`,
  );
  process.exit(1);
}
console.log(`${urlList.length} urls from ${sitemapUrl}`);

const payload = { host, key, keyLocation, urlList };
if (dryRun) {
  console.log(`\n--dry-run: would POST to ${ENDPOINT}`);
  console.log(JSON.stringify({ ...payload, urlList: [...urlList.slice(0, 3), `… ${urlList.length - 3} more`] }, null, 2));
  process.exit(0);
}

// Handled apart from fetchOrExit: a timeout on the GETs means nothing happened,
// but a timeout here is genuinely ambiguous — the submission may already have
// been accepted — and saying "failed" would be a guess. Re-running is safe
// either way (IndexNow is idempotent for a given URL set), so say that instead.
let res;
try {
  res = await fetch(ENDPOINT, {
    method: 'POST',
    headers: { 'content-type': 'application/json; charset=utf-8' },
    body: JSON.stringify(payload),
    signal: AbortSignal.timeout(30_000),
  });
} catch (err) {
  const name = err?.name;
  console.error(
    name === 'TimeoutError' || name === 'AbortError'
      ? `No response from ${ENDPOINT} within 30s. The submission may or may not have been accepted — re-running is safe.`
      : `Could not reach ${ENDPOINT} — ${err?.message ?? err}`,
  );
  process.exit(1);
}
const body = (await res.text()).trim();

// 200 accepted, 202 accepted-pending-key-validation; both are successes.
if (res.status === 200 || res.status === 202) {
  console.log(`submitted ${urlList.length} urls — HTTP ${res.status}${body ? ` ${body}` : ''}`);
} else {
  console.error(`IndexNow rejected the submission — HTTP ${res.status}${body ? ` ${body}` : ''}`);
  process.exit(1);
}
